// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static String get databaseURL {
    return 'https://amchat-bebef.firebaseio.com';
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZhsZrc2CNGVq_xdBMJN2tknEt-S_a_5s',
    appId: '1:70137099220:web:9dbcd2721aac9a340d1c41',
    messagingSenderId: '70137099220',
    projectId: 'amchat-bebef',
    authDomain: 'amchat-bebef.firebaseapp.com',
    databaseURL: 'https://amchat-bebef.firebaseio.com',
    storageBucket: 'amchat-bebef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhsZrc2CNGVq_xdBMJN2tknEt-S_a_5s',
    appId: '1:70137099220:android:9dbcd2721aac9a340d1c41',
    messagingSenderId: '70137099220',
    projectId: 'amchat-bebef',
    databaseURL: 'https://amchat-bebef.firebaseio.com',
    storageBucket: 'amchat-bebef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhsZrc2CNGVq_xdBMJN2tknEt-S_a_5s',
    appId: '1:70137099220:ios:9dbcd2721aac9a340d1c41',
    messagingSenderId: '70137099220',
    projectId: 'amchat-bebef',
    databaseURL: 'https://amchat-bebef.firebaseio.com',
    storageBucket: 'amchat-bebef.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhsZrc2CNGVq_xdBMJN2tknEt-S_a_5s',
    appId: '1:70137099220:macos:9dbcd2721aac9a340d1c41',
    messagingSenderId: '70137099220',
    projectId: 'amchat-bebef',
    databaseURL: 'https://amchat-bebef.firebaseio.com',
    storageBucket: 'amchat-bebef.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZhsZrc2CNGVq_xdBMJN2tknEt-S_a_5s',
    appId: '1:70137099220:windows:9dbcd2721aac9a340d1c41',
    messagingSenderId: '70137099220',
    projectId: 'amchat-bebef',
    databaseURL: 'https://amchat-bebef.firebaseio.com',
    storageBucket: 'amchat-bebef.firebasestorage.app',
  );
}
